language: objective-c
osx_image: xcode10.2

before_script:
    - carthage bootstrap

script:
    # Build frameworks and run tests
    - xcodebuild -project CGMBLEKit.xcodeproj -scheme Shared build -destination name="iPhone SE" test 
    # Build apps
    - xcodebuild -project CGMBLEKit.xcodeproj -scheme "CGMBLEKit Example" build -destination name="iPhone SE"
    - xcodebuild -project CGMBLEKit.xcodeproj -scheme ResetTransmitter build -destination name="iPhone SE"

